# Generated by Django 4.0.4 on 2022-04-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_types',
            new_name='super_type',
        ),
    ]
